[tool.poetry]
name = "workflow"
version = "0.1.0"
description = ""
authors = ["Reza Safari <rsafari.s@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
